name: Build

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on Ubuntu 20.04
    runs-on: ubuntu-20.04
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
        # Include all history and tags, needed for building the right version
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install datadog_checks_dev
        run: |
          python -m pip install datadog_checks_dev[cli]==20.0.1

      - name: Set ddev pypi credentials
        run: |
          ddev config set pypi.user __token__
          ddev config set pypi.pass ${{ secrets.PYPI_TOKEN }}

      - name: Publish the wheel to PyPI
        run: |
          ddev release upload . --sdist
